theme:minima
title: My GitHub page
author: GitHub User
email: vaishnavim1311@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  That's my site
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  VaishnaviMudaliar # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
